//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory_System.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccount
    {
        internal string fullname;

        public string FirstName { get; set; }
        public int userId { get; set; }
        public string LastName { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string username { get; set; }
    }
}
